### ISSUE TITLE
various issues encountered with -latest

### ISSUE THREAD

**Issue by ra1nb0w** [arclabch/network#1]
I tested the code (main/develop) with openbsd-latest uptated today.
The following errors refers to develop version.
- if I delete the [VPN] section, I receive the following error
  Can't use an undefined value as a HASH reference at /usr/local/bin/network line 118
- if I try to scan, I receive (bad regexp at line 278)
  Use of uninitialized value $1 in printf at /usr/local/bin/network line 279
  Use of uninitialized value $2 in printf at /usr/local/bin/network line 279
  Use of uninitialized value $3 in printf at /usr/local/bin/network line 279
  Use of uninitialized value $4 in printf at /usr/local/bin/network line 279
  # ifconfig iwn0 scan return
  nwid plaza chan8 bssid 1e:2e:3e:4e:5e:6e -71dBm HT-MCS15 privacy,short_preamble,short_slottime,wpa2

And some suggestions:
- scan method should print on 80 columns screen also
- chmod 640 /etc/networks.conf

Anyway, thanks a lot for your work!!

**Comment by arclabch** [comment]
Thank you for your feedback. I'll have a look soon!
